
services:
  postgres:
    image: postgres:15
    container_name: sysib-postgres
    restart: always
    environment:
      POSTGRES_USER: sysib
      POSTGRES_PASSWORD: sysib123
      POSTGRES_DB: sysib_db
    ports:
      - "5432:5432"
    volumes:
      - sysib_pgdata:/var/lib/postgresql/data

volumes:
  sysib_pgdata:
